#+ endpoint: http://fuseki:3030/TOOP/query
#+ method: GET
#+ summary: select the local data elements that are mapped to a TOOP concept

PREFIX toop: <http://toop.tno.nl/organization#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX nhr: <http://example.register.nl/nationaalhandelsregister#>

SELECT ?s ?p ?o
WHERE {
  ?s ?p ?o .	
  FILTER (?p = owl:equivalentClass)
  FILTER (STR(?s) = CONCAT("http://toop.tno.nl/organization#",?_concept))
}

